In [2]:
#import Libraries
import pandas as pd
import numpy as np
import os

In [3]:
path=r"C:\Users\abdul\Career-Foundry-Assignment4-Instacart-Basket-Analysis"

In [4]:
orders_products_merged=pd.read_pickle(os.path.join(path, '02_Data','Prepared-Data','orders_products_merged.pkl'))

In [5]:
df=orders_products_merged[:1000000]

In [6]:
df.head(5)

,Unnamed: 0.1,Unnamed: 0_x,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,Unnamed: 0_y,product_name,aisle_id,department_id,prices,_merge
0,0,0,2539329,1,prior,1,2,8,7.0,196,1,0,195,Soda,77,7,9.0,both
1,1,1,2398795,1,prior,2,3,7,15.0,196,1,1,195,Soda,77,7,9.0,both
2,2,2,473747,1,prior,3,3,12,21.0,196,1,1,195,Soda,77,7,9.0,both
3,3,3,2254736,1,prior,4,4,7,29.0,196,1,1,195,Soda,77,7,9.0,both
4,4,4,431534,1,prior,5,4,15,28.0,196,1,1,195,Soda,77,7,9.0,both

In [7]:
def price_label(row):
    if row['prices']<=5:
        return 'Low Range Product'
    elif (row['prices']>5) and (row['prices']<=15):
        return 'Medium Range Product'
    elif row['prices']>15:
        return 'High Range Product'
    else: return 'Not enough Data'

In [8]:
df['Price_range']=df.apply(price_label, axis=1)

C:\Users\abdul\AppData\Local\Temp/ipykernel_12164/2419626548.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Price_range']=df.apply(price_label, axis=1)

In [9]:
df.head(5)

,Unnamed: 0.1,Unnamed: 0_x,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,Unnamed: 0_y,product_name,aisle_id,department_id,prices,_merge,Price_range
0,0,0,2539329,1,prior,1,2,8,7.0,196,1,0,195,Soda,77,7,9.0,both,Medium Range Product
1,1,1,2398795,1,prior,2,3,7,15.0,196,1,1,195,Soda,77,7,9.0,both,Medium Range Product
2,2,2,473747,1,prior,3,3,12,21.0,196,1,1,195,Soda,77,7,9.0,both,Medium Range Product
3,3,3,2254736,1,prior,4,4,7,29.0,196,1,1,195,Soda,77,7,9.0,both,Medium Range Product
4,4,4,431534,1,prior,5,4,15,28.0,196,1,1,195,Soda,77,7,9.0,both,Medium Range Product

In [10]:
df=df.drop(columns=['_merge'])

In [11]:
df.head()

,Unnamed: 0.1,Unnamed: 0_x,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,Unnamed: 0_y,product_name,aisle_id,department_id,prices,Price_range
0,0,0,2539329,1,prior,1,2,8,7.0,196,1,0,195,Soda,77,7,9.0,Medium Range Product
1,1,1,2398795,1,prior,2,3,7,15.0,196,1,1,195,Soda,77,7,9.0,Medium Range Product
2,2,2,473747,1,prior,3,3,12,21.0,196,1,1,195,Soda,77,7,9.0,Medium Range Product
3,3,3,2254736,1,prior,4,4,7,29.0,196,1,1,195,Soda,77,7,9.0,Medium Range Product
4,4,4,431534,1,prior,5,4,15,28.0,196,1,1,195,Soda,77,7,9.0,Medium Range Product

In [12]:
df.shape

(1000000, 18)

In [13]:
df['Price_range'].value_counts()

Medium Range Product    756450
Low Range Product       243550
Name: Price_range, dtype: int64

In [14]:
df['prices'].max()

14.8

In [15]:
df.loc[df['prices']>15, 'price_range_loc']='High Range Product'

In [16]:
df.loc[(df['prices']<=15) & (df['prices']>5), 'price_range_loc']='Mid Range Product'

In [17]:
df.loc[df['prices']<=5, 'price_range_loc']='Low Range Product'

In [18]:
df['price_range_loc'].value_counts()

Mid Range Product    756450
Low Range Product    243550
Name: price_range_loc, dtype: int64

In [19]:
df.head()

,Unnamed: 0.1,Unnamed: 0_x,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,Unnamed: 0_y,product_name,aisle_id,department_id,prices,Price_range,price_range_loc
0,0,0,2539329,1,prior,1,2,8,7.0,196,1,0,195,Soda,77,7,9.0,Medium Range Product,Mid Range Product
1,1,1,2398795,1,prior,2,3,7,15.0,196,1,1,195,Soda,77,7,9.0,Medium Range Product,Mid Range Product
2,2,2,473747,1,prior,3,3,12,21.0,196,1,1,195,Soda,77,7,9.0,Medium Range Product,Mid Range Product
3,3,3,2254736,1,prior,4,4,7,29.0,196,1,1,195,Soda,77,7,9.0,Medium Range Product,Mid Range Product
4,4,4,431534,1,prior,5,4,15,28.0,196,1,1,195,Soda,77,7,9.0,Medium Range Product,Mid Range Product

In [20]:
for x in range (30,45):
    print('My age is %d' % (x))

My age is 30
My age is 31
My age is 32
My age is 33
My age is 34
My age is 35
My age is 36
My age is 37
My age is 38
My age is 39
My age is 40
My age is 41
My age is 42
My age is 43
My age is 44

In [21]:
df['order_dow'].value_counts()

1    189421
0    184410
2    133958
5    130683
6    124839
3    119801
4    116888
Name: order_dow, dtype: int64

In [24]:
result=[]
for value in df['order_dow']:
    if value==1:
        result.append("Busiest Day")
    elif value==4:
        result.append("Least Busy")
    else:
        result.append("Regulary Busy")

In [25]:
result

['Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Least Busy',
 'Regulary Busy',
 'Busiest Day',
 'Busiest Day',
 'Busiest Day',
 'Least Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Least Busy',
 'Busiest Day',
 'Busiest Day',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Busiest Day',
 'Regulary Busy',
 'Busiest Day',
 'Busiest Day',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Busiest Day',
 'Busiest Day',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Regulary Busy',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Busiest Day',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Busiest Day',
 'Busiest Day',
 'Busiest Day',
 'Regulary Busy',
 'Busiest Day',
 'Busiest Day',
 'Least Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Busiest Day',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Busiest Day',
 'Regulary Busy',
 'Busiest Day',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Busiest Day',
 'Busiest Day',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Least Busy',
 'Busiest Day',
 'Busiest Day',
 'Busiest Day',
 'Busiest Day',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Least Busy',
 'Least Busy',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Regulary Busy',
 'Least Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Busiest Day',
 'Busiest Day',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Least Busy',
 'Busiest Day',
 'Least Busy',
 'Busiest Day',
 'Busiest Day',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Least Busy',
 'Least Busy',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Regulary Busy',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Busiest Day',
 'Least Busy',
 'Busiest Day',
 'Least Busy',
 'Busiest Day',
 'Busiest Day',
 'Least Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Least Busy',
 'Regulary Busy',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Busiest Day',
 'Busiest Day',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Busiest Day',
 'Busiest Day',
 'Busiest Day',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Busiest Day',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Least Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Regulary Busy',
 'Least Busy',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Busiest Day',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Busiest Day',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Least Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Least Busy',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Least Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Least Busy',
 'Regulary Busy',
 'Least Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Busiest Day',
 'Regulary Busy',
 'Least Busy',
 'Busiest Day',
 'Busiest Day',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Busiest Day',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Least Busy',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Regulary Busy',
 'Least Busy',
 'Regulary Busy',
 'Busiest Day',
 'Busiest Day',
 'Busiest Day',
 'Busiest Day',
 'Regulary Busy',
 'Busiest Day',
 'Busiest Day',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Busiest Day',
 'Busiest Day',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Busiest Day',
 'Busiest Day',
 'Busiest Day',
 'Regulary Busy',
 'Busiest Day',
 'Busiest Day',
 'Busiest Day',
 'Busiest Day',
 'Busiest Day',
 'Busiest Day',
 'Busiest Day',
 'Busiest Day',
 'Busiest Day',
 'Regulary Busy',
 'Busiest Day',
 'Busiest Day',
 'Busiest Day',
 'Regulary Busy',
 'Busiest Day',
 'Busiest Day',
 'Busiest Day',
 'Busiest Day',
 'Busiest Day',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Busiest Day',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Least Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Least Busy',
 'Busiest Day',
 'Least Busy',
 'Least Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Least Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Least Busy',
 'Busiest Day',
 'Regulary Busy',
 'Least Busy',
 'Least Busy',
 'Regulary Busy',
 'Busiest Day',
 'Busiest Day',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Regulary Busy',
 'Least Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Busiest Day',
 'Regulary Busy',
 'Busiest Day',
 'Busiest Day',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Busiest Day',
 'Busiest Day',
 'Regulary Busy',
 'Least Busy',
 'Regulary Busy',
 'Least Busy',
 'Busiest Day',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Busiest Day',
 'Busiest Day',
 'Least Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Least Busy',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Least Busy',
 'Least Busy',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Busiest Day',
 'Busiest Day',
 'Busiest Day',
 'Busiest Day',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Busiest Day',
 'Busiest Day',
 'Least Busy',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Least Busy',
 'Least Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Least Busy',
 'Busiest Day',
 'Busiest Day',
 'Busiest Day',
 'Regulary Busy',
 'Regulary Busy',
 'Busiest Day',
 'Regulary Busy',
 'Busiest Day',
 ...]

In [26]:
df['Busiest_Day']= result

In [27]:
df.head(5)

,Unnamed: 0.1,Unnamed: 0_x,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,Unnamed: 0_y,product_name,aisle_id,department_id,prices,Price_range,price_range_loc,Busiest_Day
0,0,0,2539329,1,prior,1,2,8,7.0,196,1,0,195,Soda,77,7,9.0,Medium Range Product,Mid Range Product,Regulary Busy
1,1,1,2398795,1,prior,2,3,7,15.0,196,1,1,195,Soda,77,7,9.0,Medium Range Product,Mid Range Product,Regulary Busy
2,2,2,473747,1,prior,3,3,12,21.0,196,1,1,195,Soda,77,7,9.0,Medium Range Product,Mid Range Product,Regulary Busy
3,3,3,2254736,1,prior,4,4,7,29.0,196,1,1,195,Soda,77,7,9.0,Medium Range Product,Mid Range Product,Least Busy
4,4,4,431534,1,prior,5,4,15,28.0,196,1,1,195,Soda,77,7,9.0,Medium Range Product,Mid Range Product,Least Busy

In [28]:
df['Busiest_Day'].value_counts()

Regulary Busy    693691
Busiest Day      189421
Least Busy       116888
Name: Busiest_Day, dtype: int64