In [56]:
# import Libraries
import pandas as pd
import numpy as np
import os

In [57]:
path=r"C:\Users\abdul\Career-Foundry-Assignment4-Instacart-Basket-Analysis"

In [58]:
ords_prods_merge=pd.read_pickle(os.path.join(path, '02_Data','Prepared-Data','orders_products_merged_updated.pkl' ))

In [59]:
df=ords_prods_merge[:1000000]

In [60]:
df.shape

(1000000, 19)

In [61]:
df.head(5)

,Unnamed: 0.1,Unnamed: 0_x,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,Unnamed: 0_y,product_name,aisle_id,department_id,prices,Busiest days,busiest_period_of_day
0,0,0,2539329,1,prior,1,2,8,7.0,196,1,0,195,Soda,77,7,9.0,Regularly Busy Days,Average Orders
1,1,1,2398795,1,prior,2,3,7,15.0,196,1,1,195,Soda,77,7,9.0,Least Busy Days,Average Orders
2,2,2,473747,1,prior,3,3,12,21.0,196,1,1,195,Soda,77,7,9.0,Least Busy Days,Most Orders
3,3,3,2254736,1,prior,4,4,7,29.0,196,1,1,195,Soda,77,7,9.0,Least Busy Days,Average Orders
4,4,4,431534,1,prior,5,4,15,28.0,196,1,1,195,Soda,77,7,9.0,Least Busy Days,Most Orders

In [62]:
df.groupby('product_name')

In [63]:
df.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
4                18.825780
7                17.472355
13               17.993423
14               19.246334
16               19.463012
17               11.294069
19               19.305237
20               17.599636

In [64]:
df.groupby('department_id')['order_number'].mean()

department_id
4     18.825780
7     17.472355
13    17.993423
14    19.246334
16    19.463012
17    11.294069
19    19.305237
20    17.599636
Name: order_number, dtype: float64

In [65]:
df.groupby('department_id').order_number.mean()

department_id
4     18.825780
7     17.472355
13    17.993423
14    19.246334
16    19.463012
17    11.294069
19    19.305237
20    17.599636
Name: order_number, dtype: float64

In [66]:
df.groupby('department_id').agg({'order_number': ['mean', 'min', 'max']})

              order_number
                      mean min max
department_id
4                18.825780   1  99
7                17.472355   1  99
13               17.993423   1  99
14               19.246334   1  99
16               19.463012   1  99
17               11.294069   1  98
19               19.305237   1  99
20               17.599636   1  99

In [67]:
df.groupby('user_id').agg({'order_number': ['max']})

        order_number
                 max
user_id
1                 10
2                 14
3                 12
5                  4
7                 17
...              ...
206205             1
206206            40
206207            16
206208            49
206209             8

[124698 rows x 1 columns]

In [68]:
ords_prods_merge['max_order']=ords_prods_merge.groupby(['user_id'])['order_number'].transform(np.max)

In [69]:
ords_prods_merge.head(60)

,Unnamed: 0.1,Unnamed: 0_x,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,Unnamed: 0_y,product_name,aisle_id,department_id,prices,Busiest days,busiest_period_of_day,max_order
0,0,0,2539329,1,prior,1,2,8,7.0,196,1,0,195,Soda,77,7,9.0,Regularly Busy Days,Average Orders,10
1,1,1,2398795,1,prior,2,3,7,15.0,196,1,1,195,Soda,77,7,9.0,Least Busy Days,Average Orders,10
2,2,2,473747,1,prior,3,3,12,21.0,196,1,1,195,Soda,77,7,9.0,Least Busy Days,Most Orders,10
3,3,3,2254736,1,prior,4,4,7,29.0,196,1,1,195,Soda,77,7,9.0,Least Busy Days,Average Orders,10
4,4,4,431534,1,prior,5,4,15,28.0,196,1,1,195,Soda,77,7,9.0,Least Busy Days,Most Orders,10
5,5,5,3367565,1,prior,6,2,7,19.0,196,1,1,195,Soda,77,7,9.0,Regularly Busy Days,Average Orders,10
6,6,6,550135,1,prior,7,1,9,20.0,196,1,1,195,Soda,77,7,9.0,Busiest Days,Most Orders,10
7,7,7,3108588,1,prior,8,1,14,14.0,196,2,1,195,Soda,77,7,9.0,Busiest Days,Most Orders,10
8,8,8,2295261,1,prior,9,1,16,0.0,196,4,1,195,Soda,77,7,9.0,Busiest Days,Most Orders,10
9,9,9,2550362,1,prior,10,4,8,30.0,196,1,1,195,Soda,77,7,9.0,Least Busy Days,Average Orders,10
10,144,144,2968173,15,prior,15,1,9,7.0,196,2,0,195,Soda,77,7,9.0,Busiest Days,Most Orders,22
11,146,146,1870022,15,prior,17,2,16,8.0,196,6,1,195,Soda,77,7,9.0,Regularly Busy Days,Most Orders,22
12,147,147,1911383,15,prior,18,2,11,7.0,196,1,1,195,Soda,77,7,9.0,Regularly Busy Days,Most Orders,22
13,150,150,2715276,15,prior,21,1,9,7.0,196,1,1,195,Soda,77,7,9.0,Busiest Days,Most Orders,22
14,151,151,487368,15,prior,22,1,10,14.0,196,1,1,195,Soda,77,7,9.0,Busiest Days,Most Orders,22
15,209,209,2293453,19,prior,2,5,14,6.0,196,3,0,195,Soda,77,7,9.0,Regularly Busy Days,Most Orders,9
16,212,212,1973799,19,prior,5,6,12,8.0,196,15,1,195,Soda,77,7,9.0,Regularly Busy Days,Most Orders,9
17,214,214,532817,19,prior,7,4,17,6.0,196,1,1,195,Soda,77,7,9.0,Least Busy Days,Average Orders,9
18,232,232,1573906,21,prior,10,3,10,6.0,196,2,0,195,Soda,77,7,9.0,Least Busy Days,Most Orders,33
19,458,458,1593000,31,prior,10,3,8,7.0,196,17,0,195,Soda,77,7,9.0,Least Busy Days,Average Orders,20
20,465,465,2231262,31,prior,17,3,11,8.0,196,14,1,195,Soda,77,7,9.0,Least Busy Days,Most Orders,20
21,617,617,2580647,43,prior,6,4,16,4.0,196,9,0,195,Soda,77,7,9.0,Least Busy Days,Most Orders,11
22,620,620,2187180,43,prior,9,4,12,3.0,196,1,1,195,Soda,77,7,9.0,Least Busy Days,Most Orders,11
23,751,751,2497897,52,prior,1,1,9,7.0,196,4,0,195,Soda,77,7,9.0,Busiest Days,Most Orders,27
24,752,752,1318871,52,prior,2,1,10,7.0,196,5,1,195,Soda,77,7,9.0,Busiest Days,Most Orders,27
25,753,753,1261384,52,prior,3,1,10,7.0,196,3,1,195,Soda,77,7,9.0,Busiest Days,Most Orders,27
26,755,755,580568,52,prior,5,2,10,8.0,196,6,1,195,Soda,77,7,9.0,Regularly Busy Days,Most Orders,27
27,757,757,2428073,52,prior,7,2,7,8.0,196,5,1,195,Soda,77,7,9.0,Regularly Busy Days,Average Orders,27
28,759,759,342306,52,prior,9,1,11,7.0,196,5,1,195,Soda,77,7,9.0,Busiest Days,Most Orders,27
29,760,760,1520353,52,prior,10,2,10,8.0,196,4,1,195,Soda,77,7,9.0,Regularly Busy Days,Most Orders,27
30,761,761,2542086,52,prior,11,2,9,7.0,196,3,1,195,Soda,77,7,9.0,Regularly Busy Days,Most Orders,27
31,762,762,944694,52,prior,12,1,16,6.0,196,7,1,195,Soda,77,7,9.0,Busiest Days,Most Orders,27
32,765,765,1268191,52,prior,15,2,11,8.0,196,3,1,195,Soda,77,7,9.0,Regularly Busy Days,Most Orders,27
33,767,767,1122089,52,prior,17,2,10,6.0,196,4,1,195,Soda,77,7,9.0,Regularly Busy Days,Most Orders,27
34,768,768,1498922,52,prior,18,2,10,14.0,196,6,1,195,Soda,77,7,9.0,Regularly Busy Days,Most Orders,27
35,769,769,180919,52,prior,19,3,8,8.0,196,4,1,195,Soda,77,7,9.0,Least Busy Days,Average Orders,27
36,771,771,2695875,52,prior,21,5,10,30.0,196,1,1,195,Soda,77,7,9.0,Regularly Busy Days,Most Orders,27
37,1022,1022,3205960,67,prior,1,3,11,7.0,196,1,0,195,Soda,77,7,9.0,Least Busy Days,Most Orders,24
38,1023,1023,970922,67,prior,2,1,15,5.0,196,2,1,195,Soda,77,7,9.0,Busiest Days,Most Orders,24
39,1024,1024,596585,67,prior,3,1,13,7.0,196,2,1,195,Soda,77,7,9.0,Busiest Days,Most Orders,24
40,1025,1025,2037087,67,prior,4,2,9,8.0,196,1,1,195,Soda,77,7,9.0,Regularly Busy Days,Most Orders,24
41,1026,1026,2474111,67,prior,5,3,14,8.0,196,2,1,195,Soda,77,7,9.0,Least Busy Days,Most Orders,24
42,1027,1027,1568481,67,prior,6,3,12,7.0,196,2,1,195,Soda,77,7,9.0,Least Busy Days,Most Orders,24
43,1029,1029,2048527,67,prior,8,2,11,7.0,196,1,1,195,Soda,77,7,9.0,Regularly Busy Days,Most Orders,24
44,1030,1030,2389031,67,prior,9,2,14,7.0,196,1,1,195,Soda,77,7,9.0,Regularly Busy Days,Most Orders,24
45,1031,1031,2378562,67,prior,10,1,10,6.0,196,1,1,195,Soda,77,7,9.0,Busiest Days,Most Orders,24
46,1032,1032,1515698,67,prior,11,1,11,7.0,196,1,1,195,Soda,77,7,9.0,Busiest Days,Most Orders,24
47,1033,1033,1928050,67,prior,12,2,12,8.0,196,1,1,195,Soda,77,7,9.0,Regularly Busy Days,Most Orders,24
48,1034,1034,1949274,67,prior,13,1,10,6.0,196,1,1,195,Soda,77,7,9.0,Busiest Days,Most Orders,24
49,1035,1035,551869,67,prior,14,1,9,7.0,196,1,1,195,Soda,77,7,9.0,Busiest Days,Most Orders,24
50,1037,1037,768572,67,prior,16,4,10,9.0,196,1,1,195,Soda,77,7,9.0,Least Busy Days,Most Orders,24
51,1039,1039,150528,67,prior,18,5,16,4.0,196,1,1,195,Soda,77,7,9.0,Regularly Busy Days,Most Orders,24
52,1040,1040,29758,67,prior,19,0,14,9.0,196,2,1,195,Soda,77,7,9.0,Busiest Days,Most Orders,24
53,1042,1042,1558976,67,prior,21,1,9,5.0,196,2,1,195,Soda,77,7,9.0,Busiest Days,Most Orders,24
54,1043,1043,863974,67,prior,22,1,11,14.0,196,3,1,195,Soda,77,7,9.0,Busiest Days,Most Orders,24
55,1044,1044,2308399,67,prior,23,1,14,14.0,196,1,1,195,Soda,77,7,9.0,Busiest Days,Most Orders,24
56,1202,1202,2759128,81,prior,3,1,9,14.0,196,2,0,195,Soda,77,7,9.0,Busiest Days,Most Orders,7
57,1204,1204,1812985,81,prior,5,2,20,30.0,196,1,1,195,Soda,77,7,9.0,Regularly Busy Days,Average Orders,7
58,1208,1208,1889835,82,prior,1,3,15,7.0,196,6,0,195,Soda,77,7,9.0,Least Busy Days,Most Orders,19
59,1210,1210,499460,82,prior,3,5,10,5.0,196,2,1,195,Soda,77,7,9.0,Regularly Busy Days,Most Orders,19

In [70]:
ords_prods_merge.loc[ords_prods_merge['max_order']>40, 'loyalty_flag']='Loyal Customer'

In [71]:
ords_prods_merge.loc[(ords_prods_merge['max_order']<=40) & (ords_prods_merge['max_order']>10), 'loyalty_flag']='Regular Customer'

In [72]:
ords_prods_merge.loc[ords_prods_merge['max_order']<=10, 'loyalty_flag']='New Customer'

In [73]:
ords_prods_merge.head(15)

,Unnamed: 0.1,Unnamed: 0_x,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,...,reordered,Unnamed: 0_y,product_name,aisle_id,department_id,prices,Busiest days,busiest_period_of_day,max_order,loyalty_flag
0,0,0,2539329,1,prior,1,2,8,7.0,196,...,0,195,Soda,77,7,9.0,Regularly Busy Days,Average Orders,10,New Customer
1,1,1,2398795,1,prior,2,3,7,15.0,196,...,1,195,Soda,77,7,9.0,Least Busy Days,Average Orders,10,New Customer
2,2,2,473747,1,prior,3,3,12,21.0,196,...,1,195,Soda,77,7,9.0,Least Busy Days,Most Orders,10,New Customer
3,3,3,2254736,1,prior,4,4,7,29.0,196,...,1,195,Soda,77,7,9.0,Least Busy Days,Average Orders,10,New Customer
4,4,4,431534,1,prior,5,4,15,28.0,196,...,1,195,Soda,77,7,9.0,Least Busy Days,Most Orders,10,New Customer
5,5,5,3367565,1,prior,6,2,7,19.0,196,...,1,195,Soda,77,7,9.0,Regularly Busy Days,Average Orders,10,New Customer
6,6,6,550135,1,prior,7,1,9,20.0,196,...,1,195,Soda,77,7,9.0,Busiest Days,Most Orders,10,New Customer
7,7,7,3108588,1,prior,8,1,14,14.0,196,...,1,195,Soda,77,7,9.0,Busiest Days,Most Orders,10,New Customer
8,8,8,2295261,1,prior,9,1,16,0.0,196,...,1,195,Soda,77,7,9.0,Busiest Days,Most Orders,10,New Customer
9,9,9,2550362,1,prior,10,4,8,30.0,196,...,1,195,Soda,77,7,9.0,Least Busy Days,Average Orders,10,New Customer
10,144,144,2968173,15,prior,15,1,9,7.0,196,...,0,195,Soda,77,7,9.0,Busiest Days,Most Orders,22,Regular Customer
11,146,146,1870022,15,prior,17,2,16,8.0,196,...,1,195,Soda,77,7,9.0,Regularly Busy Days,Most Orders,22,Regular Customer
12,147,147,1911383,15,prior,18,2,11,7.0,196,...,1,195,Soda,77,7,9.0,Regularly Busy Days,Most Orders,22,Regular Customer
13,150,150,2715276,15,prior,21,1,9,7.0,196,...,1,195,Soda,77,7,9.0,Busiest Days,Most Orders,22,Regular Customer
14,151,151,487368,15,prior,22,1,10,14.0,196,...,1,195,Soda,77,7,9.0,Busiest Days,Most Orders,22,Regular Customer

In [74]:
ords_prods_merge['loyalty_flag'].value_counts()

Regular Customer    15876776
Loyal Customer      10284093
New Customer         6243990
Name: loyalty_flag, dtype: int64

In [75]:
ords_prods_merge[['user_id', 'order_number','max_order','loyalty_flag' ]].head(60)

    user_id  order_number  max_order      loyalty_flag
0         1             1         10      New Customer
1         1             2         10      New Customer
2         1             3         10      New Customer
3         1             4         10      New Customer
4         1             5         10      New Customer
5         1             6         10      New Customer
6         1             7         10      New Customer
7         1             8         10      New Customer
8         1             9         10      New Customer
9         1            10         10      New Customer
10       15            15         22  Regular Customer
11       15            17         22  Regular Customer
12       15            18         22  Regular Customer
13       15            21         22  Regular Customer
14       15            22         22  Regular Customer
15       19             2          9      New Customer
16       19             5          9      New Customer
17       19             7          9      New Customer
18       21            10         33  Regular Customer
19       31            10         20  Regular Customer
20       31            17         20  Regular Customer
21       43             6         11  Regular Customer
22       43             9         11  Regular Customer
23       52             1         27  Regular Customer
24       52             2         27  Regular Customer
25       52             3         27  Regular Customer
26       52             5         27  Regular Customer
27       52             7         27  Regular Customer
28       52             9         27  Regular Customer
29       52            10         27  Regular Customer
30       52            11         27  Regular Customer
31       52            12         27  Regular Customer
32       52            15         27  Regular Customer
33       52            17         27  Regular Customer
34       52            18         27  Regular Customer
35       52            19         27  Regular Customer
36       52            21         27  Regular Customer
37       67             1         24  Regular Customer
38       67             2         24  Regular Customer
39       67             3         24  Regular Customer
40       67             4         24  Regular Customer
41       67             5         24  Regular Customer
42       67             6         24  Regular Customer
43       67             8         24  Regular Customer
44       67             9         24  Regular Customer
45       67            10         24  Regular Customer
46       67            11         24  Regular Customer
47       67            12         24  Regular Customer
48       67            13         24  Regular Customer
49       67            14         24  Regular Customer
50       67            16         24  Regular Customer
51       67            18         24  Regular Customer
52       67            19         24  Regular Customer
53       67            21         24  Regular Customer
54       67            22         24  Regular Customer
55       67            23         24  Regular Customer
56       81             3          7      New Customer
57       81             5          7      New Customer
58       82             1         19  Regular Customer
59       82             3         19  Regular Customer